### ISSUE TITLE
${workspaceFolder} not resolving — agent uses wrong workspace path

### ISSUE THREAD

**Issue by huydepzai121** [augmentcode/auggie-zed-extension#4]
When running the Auggie agent in Zed, the ${workspaceFolder} variable is not resolved to the current workspace that is open in Zed.
Instead, the agent receives the path of the extracted package directory (for example:
C:\Users\<User>\AppData\Local\Zed\agent_servers\auggie\package\)
instead of the actual project folder that Zed is editing.

I didn’t create any wrapper script — just using the default auggie agent config.
It would be better if Auggie automatically detected and used the real workspace path that Zed has opened.

**Comment by mtpauly** [comment]
Hi @huydepzai121 , there was an issue with Zed not passing the correct directory but this should be resolved as of the latest version 0.211.6 (which was released yesterday afternoon). Could you confirm your Zed version?

**Comment by hussain** [comment]
I'm on Zed Preview 0.212.2 and I can confirm issue still exist.



<img width="1306" height="828" alt="Image" src="https://github.com/user-attachments/assets/a88d70db-6bc0-44cb-addd-f45c1c7014bf" />

**Comment by mtpauly** [comment]
Hi @hussain , the fix should currently be in the latest stable (0.211.6) but won't be in the preview version until tomorrow's preview release. This is due to the fact that the fix was deployed on an accelerated timeline. Could you confirm that it's working on the stable version?

**Comment by mtpauly** [comment]
I tested on the latest prerelease 0.213.0 (and the stable) and confirmed that this is working, I'm going to mark this as closed. If you continue to see the issue feel free to reopen or create a new thread.

**Comment by huydepzai121** [comment]
@mtpauly Version 0.213.0 stable has the same bug but 0.211.6 does not.

**Comment by hussain** [comment]
0.213.0 is working for me! on both Windows 11 directly & Windows+WSL

**Comment by mtpauly** [comment]
@huydepzai121 version 0.213.0 is a preview release, not a stable, but either way the bug should be patched there. Are you positive you're on that version? You might need to reload the workspace after Zed auto updates.
